### ISSUE TITLE
ImportError: OrderedDict using Google Colab environment

### ISSUE THREAD

**Issue by blsymens** [DOV-Vlaanderen/pydov#282] opened 2020-06-02 20:51 UTC
* PyDOV version: 1.0.0
* Python version: 3.6
* Operating System: Google Colab VM

### Description
Open github repository in via Google Colab using this url: [https://colab.research.google.com/github/](url). 
After installing pydov, I was trying to run the code to visualise some data. 
`!pip install pydov`

```
from pydov.search.grondwaterfilter import GrondwaterFilterSearch
gwfilter = GrondwaterFilterSearch()
```
So far so good. 
 
```
from pydov.util.location import Within, Box

df = gwfilter.search(location=Within(Box(93378, 168009, 94246, 169873)))
df.head()
```

### What I Did

```
[000/026] ..........................
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

2 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _repr_html_(self)
    732         Property returning a Styler object containing methods for
    733         building a styled HTML representation fo the DataFrame.
--> 734 
    735         See Also
    736         --------

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/format.py in to_html(self, buf, encoding, classes, notebook, border)
    977                     # False specifically, so that the default is
    978                     # to include a space if we get here.
--> 979                     tpl = u'{v}'
    980                 else:
    981                     tpl = u' {v}'

/usr/local/lib/python3.6/dist-packages/pandas/io/formats/html.py in <module>()
      8 from textwrap import dedent
      9 
---> 10 from pandas.compat import OrderedDict, lzip, map, range, u, unichr, zip
     11 
     12 from pandas.core.dtypes.generic import ABCMultiIndex

ImportError: cannot import name 'OrderedDict'
                                         pkey_filter  ... filtertoestand
0  https://www.dov.vlaanderen.be/data/filter/1999...  ...            1.0
1  https://www.dov.vlaanderen.be/data/filter/1999...  ...            1.0
2  https://www.dov.vlaanderen.be/data/filter/1999...  ...            1.0
3  https://www.dov.vlaanderen.be/data/filter/1999...  ...            1.0
4  https://www.dov.vlaanderen.be/data/filter/1999...  ...            1.0

[5 rows x 22 columns]
```

**Comment by stijnvanhoey** [comment] 2020-06-03 08:29
@blsymens thanks for the report. 

Can you have a check on the pandas version your working with? e.g. using 

```
import pandas as pd
pd.__version__
```

**Comment by blsymens** [comment] 2020-06-03 13:32
Version pandas: 1.0.4 .

Link to notebook:
https://colab.research.google.com/github/DOV-Vlaanderen/pydov/blob/master/docs/notebooks/search_grondwaterfilters.ipynb


Op wo 3 jun. 2020 om 10:29 schreef Stijn Van Hoey <notifications@github.com

**Comment by Roel** [comment] 2020-06-03 13:46
I can reproduce your error when I install pydov with pip inside the notebook and then continue without restarting the runtime. After restarting the runtime (as mentioned in the output of the pip command, see below) I cannot reproduce the error. Did you try restarting the runtime after installing pydov (i.e. pandas)?

```
WARNING: The following packages were previously imported in this runtime:
  [numpy,pandas]
You must restart the runtime in order to use newly installed versions.
```

**Comment by blsymens** [comment] 2020-06-03 15:03
Ahaa, no I haven't. I didn't pay too much attention to what the output
said. Than problem seems to be solved. No real bug.

Thanks for your help.

Bavo

**Comment by Roel** [comment] 2020-06-03 16:07
You're welcome! I'm going to close this issue, but don't hesitate to open a new one should you have any further questions!

**Closed by Roel** 2020-06-03 16:07 UTC
