### ISSUE TITLE
branch poc_boring

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#41] opened 2018-01-26 15:03 UTC
* PyDOV version: branch poc_boring
* Python version: 2.7.5 OSGeo4W distribution for QGIS 2.14 ltr
* Operating System: Windows

### Description

Testing branch _poc_boring_ yielded some initial dependency issues on the OSGeo4W python distribution:

- The owslib module is not up-to-date with the one tested by Roel: the _schema.py_ (owslib/feature/) and other methods are missing.

- Therefore, I downloaded the current master from GitHub and replaced this in OSGeo4W\apps\qgis-ltr\python\owslib

Then some warning messages pop-up, which I don't know if we should care about too much at the moment?

- following openURL on line 54 of owslib\feature\common.py:

```
C:\OSGEO4~1\apps\Python27\Lib\site-packages\urllib3\util\ssl_.py:339: SNIMissingWarning: 
An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS 
is not available on this platform. This may cause the server to present an incorrect TLS certificate, 
which can cause validation failures. 
You can upgrade to a newer version of Python to solve this. For more information, see 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning

C:\OSGEO4~1\apps\Python27\Lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: 
A true SSLContext object is not available. 
This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. 
You can upgrade to a newer version of Python to solve this. 
For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
````
- or after calling get_fields() in the boring_search.py examples
````
return self.__wfs.contents[self._layer] on line 104 of pydov/search.py returns:
C:\OSGEO4~1\apps\qgis-ltr\python\owslib\iso.py:116: FutureWarning: the .identification 
and .serviceidentification properties will merge into .identification being a list of properties.  
This is currently implemented in .identificationinfo.  Please see
ttps://github.com/geopython/OWSLib/issues/38 for more information
  FutureWarning)
````
- the pkey_boring link is not printed correctly, but it is ok in the dataframe, no worries

Overall +1! More testing with new queries will follow.

**Comment by Roel** [comment] 2018-01-26 19:01
A test setup for automated testing against OSGeo4W would be useful (this is issue #25).

You should not need to get owslib from git, a recently released version (0.15 or 0.16) should work too. Which version is included in your OSGeo4W installation?
I think this can be fixed by updating your OSGeo4W installation.

The first two warnings are due to missing SSL/TLS features in your Python version and will disappear in more recent versions (I've never seen them on my system).
This might be fixed as well by updating you OSGeo4W installation.

The last warning is one I've seen before and originates from owslib, but I think it can safely be ignored.

**Comment by pjhaest** [comment] 2018-01-27 22:43
I'm running owslib 0.14 from OSGeo4W for QGIS 2.14 ltr with a fresh install. I cannot upgrade owslib beyond 0.14 using the OSGeo installer. I will see if I can upgrade to QGIS 2.18.
Anyway, this was a minor issue if you don't see these warnings. Results come out ok.
However, good to mention somewhere the necessity of owlisb 0.15 or higher.

**Comment by Roel** [comment] 2018-01-28 10:00
I tested locally using owslib 0.14 and everything still seems to work.. I checked in git and the schema.py seems to be included as of version 0.11. I'll test with an OSGeo4W installation next to see what's going on. :)

**Comment by Roel** [comment] 2018-01-29 08:39
I can reproduce the warnings on my local install of OSGeo4W, but I think these can be ignored. However I cannot reproduce the missing schema.py from oswlib: after installing pandas everything works fine here.

Note that you have to start python from the OSGeo4W shell, not from a regular shell: in the last case the environment variables are not set, so python cannot find or import the libraries installed with OSGeo4W.

**Comment by pjhaest** [comment] 2018-01-29 10:18
Ok, that can be the issue. I reproduced the .bat startup of QGIS to run my IDE, giving access to the libraries in OSGeo4W. But maybe PyCharm didn't track the 'correct' path to the specific owslib installation as I didn't configure the paths in my IDE. Will change that.

**Closed** 2018-05-08 10:01 UTC
